/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtistCredit: typeof import('./src/components/ArtistCredit.vue')['default']
    BackgroundImage: typeof import('./src/components/BackgroundImage.vue')['default']
    ClockDisplay: typeof import('./src/components/ClockDisplay.vue')['default']
    DashboardControls: typeof import('./src/components/DashboardControls.vue')['default']
    FirstRunModal: typeof import('./src/components/FirstRunModal.vue')['default']
    GreetingMessage: typeof import('./src/components/GreetingMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    TopSites: typeof import('./src/components/TopSites.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
